[build]
  command = "npm ci --include=dev && npm run build"
  publish = "out"

[images]
  remote_images = [
    "https://source.unsplash.com/.*",
    "https://images.unsplash.com/.*",
    "https://ext.same-assets.com/.*",
    "https://ugc.same-assets.com/.*"
  ]

[build.environment]
  # Next.js Configuration
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NODE_ENV = "production"
  
  # TurpoPlay specific
  NEXT_PUBLIC_SITE_URL = "https://turbo-play.live"
  NEXT_PUBLIC_APP_NAME = "TurpoPlay"
  
  # Meta Pixel Configuration
  NEXT_PUBLIC_META_PIXEL_ID = "750660614671785"
  # Meta Pixel Access Token - Добавить через Netlify UI как SECRET!
  # META_PIXEL_ACCESS_TOKEN = "your-secret-token-here"

# Основные заголовки безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Country = "{{country}}"
    X-Language = "{{language}}"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Edge Functions для защиты от ботов
[[edge_functions]]
  function = "bot-redirect"
  path = "/*"

# Кэширование статических ресурсов
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Кэширование изображений
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Редиректы для SEO
[[redirects]]
  from = "/wheel"
  to = "/"
  status = 301

[[redirects]]
  from = "/fortune"
  to = "/"
  status = 301

[[redirects]]
  from = "/casino"
  to = "/"
  status = 301
